---
stages:
  - build
build-frontend:
  stage: build
  image: node:16.9.0
  before_script:
    - cd Recruitment-FE/
    - npm ci
  script:
    - npm run build
build-backend:
  stage: build
  image: microsoft/dotnet:latest
  before_script:
    - cd Recruitment-Web-API/
    - dotnet restore
  script:
    - dotnet build